<?php

namespace Database\Seeders;

use App\Models\IrregularVerb;
use Illuminate\Database\Seeder;

class IrregularVerbSeeder extends Seeder
{
    public function run(): void
    {
        $verbs = [
            ['infinitive' => 'arise', 'past_simple' => 'arose', 'past_participle' => 'arisen', 'meaning_hu' => 'felmerül, keletkezik', 'example_en' => 'A problem arose just before the deadline.'],
            ['infinitive' => 'be', 'past_simple' => 'was/were', 'past_participle' => 'been', 'meaning_hu' => 'van, lenni', 'example_en' => 'I want to be a doctor when I grow up.'],
            ['infinitive' => 'bear', 'past_simple' => 'bore', 'past_participle' => 'borne', 'meaning_hu' => 'elvisel, medve', 'example_en' => 'She could not bear the loud noise any longer.'],
            ['infinitive' => 'beat', 'past_simple' => 'beat', 'past_participle' => 'beaten', 'meaning_hu' => 'megver, legyőz', 'example_en' => 'Our team beat the opponents by three goals.'],
            ['infinitive' => 'become', 'past_simple' => 'became', 'past_participle' => 'become', 'meaning_hu' => 'lesz, válik valamivé', 'example_en' => 'He became a famous writer after years of hard work.'],
            ['infinitive' => 'begin', 'past_simple' => 'began', 'past_participle' => 'begun', 'meaning_hu' => 'kezd, elkezd', 'example_en' => 'The concert will begin at eight o\'clock.'],
            ['infinitive' => 'bend', 'past_simple' => 'bent', 'past_participle' => 'bent', 'meaning_hu' => 'hajlít, kanyar', 'example_en' => 'She had to bend down to pick up the coin from the floor.'],
            ['infinitive' => 'bet', 'past_simple' => 'bet', 'past_participle' => 'bet', 'meaning_hu' => 'fogad, fogadás', 'example_en' => 'I bet you cannot eat the whole cake.'],
            ['infinitive' => 'bind', 'past_simple' => 'bound', 'past_participle' => 'bound', 'meaning_hu' => 'köt, kötelez', 'example_en' => 'She bound the papers together with a rubber band.'],
            ['infinitive' => 'bite', 'past_simple' => 'bit', 'past_participle' => 'bitten', 'meaning_hu' => 'harap, marás', 'example_en' => 'She was bitten by a mosquito in the garden.'],
            ['infinitive' => 'bleed', 'past_simple' => 'bled', 'past_participle' => 'bled', 'meaning_hu' => 'vérzik, véreztet', 'example_en' => 'She cut her finger and it started to bleed.'],
            ['infinitive' => 'blow', 'past_simple' => 'blew', 'past_participle' => 'blown', 'meaning_hu' => 'fúj, fújás', 'example_en' => 'The wind blew the hat off her head.'],
            ['infinitive' => 'break', 'past_simple' => 'broke', 'past_participle' => 'broken', 'meaning_hu' => 'tör, szünet', 'example_en' => 'Be careful not to break the glass.'],
            ['infinitive' => 'breed', 'past_simple' => 'bred', 'past_participle' => 'bred', 'meaning_hu' => 'tenyészt, faj', 'example_en' => 'She breeds dogs as a hobby on her farm.'],
            ['infinitive' => 'bring', 'past_simple' => 'brought', 'past_participle' => 'brought', 'meaning_hu' => 'hoz, elhoz', 'example_en' => 'Can you bring me a glass of water, please?'],
            ['infinitive' => 'broadcast', 'past_simple' => 'broadcast', 'past_participle' => 'broadcast', 'meaning_hu' => 'sugároz, közvetít', 'example_en' => 'She broadcast the news live from the scene.'],
            ['infinitive' => 'build', 'past_simple' => 'built', 'past_participle' => 'built', 'meaning_hu' => 'épít, felépít', 'example_en' => 'They plan to build a new hospital in the city.'],
            ['infinitive' => 'burst', 'past_simple' => 'burst', 'past_participle' => 'burst', 'meaning_hu' => 'robban, szétreped', 'example_en' => 'The pipe burst and flooded the whole kitchen.'],
            ['infinitive' => 'buy', 'past_simple' => 'bought', 'past_participle' => 'bought', 'meaning_hu' => 'vásárol, megvesz', 'example_en' => 'I need to buy some groceries on the way home.'],
            ['infinitive' => 'cast', 'past_simple' => 'cast', 'past_participle' => 'cast', 'meaning_hu' => 'dob, szereplőgárda', 'example_en' => 'She was cast as the lead role in the school play.'],
            ['infinitive' => 'catch', 'past_simple' => 'caught', 'past_participle' => 'caught', 'meaning_hu' => 'fog, elkap', 'example_en' => 'She managed to catch the ball with one hand.'],
            ['infinitive' => 'choose', 'past_simple' => 'chose', 'past_participle' => 'chosen', 'meaning_hu' => 'választ, kiválaszt', 'example_en' => 'It is hard to choose between so many options.'],
            ['infinitive' => 'cling', 'past_simple' => 'clung', 'past_participle' => 'clung', 'meaning_hu' => 'ragaszkodik, tapad', 'example_en' => 'She clung to her belief despite the challenges.'],
            ['infinitive' => 'come', 'past_simple' => 'came', 'past_participle' => 'come', 'meaning_hu' => 'jön, érkezik', 'example_en' => 'Can you come to my party on Saturday?'],
            ['infinitive' => 'cost', 'past_simple' => 'cost', 'past_participle' => 'cost', 'meaning_hu' => 'kerül, ár', 'example_en' => 'How much does a train ticket to the airport cost?'],
            ['infinitive' => 'creep', 'past_simple' => 'crept', 'past_participle' => 'crept', 'meaning_hu' => 'kúszik, oson', 'example_en' => 'She crept quietly into the room so as not to wake anyone.'],
            ['infinitive' => 'cut', 'past_simple' => 'cut', 'past_participle' => 'cut', 'meaning_hu' => 'vág, metszet', 'example_en' => 'She cut the bread into thin slices.'],
            ['infinitive' => 'deal', 'past_simple' => 'dealt', 'past_participle' => 'dealt', 'meaning_hu' => 'üzlet, foglalkozik', 'example_en' => 'They made a deal to share the costs equally.'],
            ['infinitive' => 'dig', 'past_simple' => 'dug', 'past_participle' => 'dug', 'meaning_hu' => 'ás, túr', 'example_en' => 'The dog dug a hole in the garden to bury the bone.'],
            ['infinitive' => 'do', 'past_simple' => 'did', 'past_participle' => 'done', 'meaning_hu' => 'tesz, csinál', 'example_en' => 'What do you usually do at weekends?'],
            ['infinitive' => 'draw', 'past_simple' => 'drew', 'past_participle' => 'drawn', 'meaning_hu' => 'rajzol, húz', 'example_en' => 'She likes to draw portraits of her friends.'],
            ['infinitive' => 'drink', 'past_simple' => 'drank', 'past_participle' => 'drunk', 'meaning_hu' => 'iszik, ital', 'example_en' => 'It is important to drink enough water every day.'],
            ['infinitive' => 'drive', 'past_simple' => 'drove', 'past_participle' => 'driven', 'meaning_hu' => 'vezet, hajt', 'example_en' => 'She drives to work every day in heavy traffic.'],
            ['infinitive' => 'dwell', 'past_simple' => 'dwelt', 'past_participle' => 'dwelt', 'meaning_hu' => 'lakik, időzik', 'example_en' => 'She chose not to dwell on past mistakes.'],
            ['infinitive' => 'eat', 'past_simple' => 'ate', 'past_participle' => 'eaten', 'meaning_hu' => 'eszik, fogyaszt', 'example_en' => 'She tries to eat a healthy lunch every day.'],
            ['infinitive' => 'fall', 'past_simple' => 'fell', 'past_participle' => 'fallen', 'meaning_hu' => 'esik, ősz', 'example_en' => 'Be careful not to fall on the icy pavement.'],
            ['infinitive' => 'feed', 'past_simple' => 'fed', 'past_participle' => 'fed', 'meaning_hu' => 'etet, táplál', 'example_en' => 'She feeds the ducks at the pond every Sunday.'],
            ['infinitive' => 'feel', 'past_simple' => 'felt', 'past_participle' => 'felt', 'meaning_hu' => 'érez, tapint', 'example_en' => 'How do you feel after your long journey?'],
            ['infinitive' => 'fight', 'past_simple' => 'fought', 'past_participle' => 'fought', 'meaning_hu' => 'harc, verekedik', 'example_en' => 'They had to fight hard to win the championship.'],
            ['infinitive' => 'find', 'past_simple' => 'found', 'past_participle' => 'found', 'meaning_hu' => 'talál, megtalál', 'example_en' => 'Did you find the keys you were looking for?'],
            ['infinitive' => 'flee', 'past_simple' => 'fled', 'past_participle' => 'fled', 'meaning_hu' => 'menekül, elmenekül', 'example_en' => 'She fled the country during the conflict.'],
            ['infinitive' => 'fling', 'past_simple' => 'flung', 'past_participle' => 'flung', 'meaning_hu' => 'hajít, dobás', 'example_en' => 'She flung the door open and ran inside.'],
            ['infinitive' => 'fly', 'past_simple' => 'flew', 'past_participle' => 'flown', 'meaning_hu' => 'repül, légy', 'example_en' => 'Birds fly south for the winter every year.'],
            ['infinitive' => 'forbid', 'past_simple' => 'forbade', 'past_participle' => 'forbidden', 'meaning_hu' => 'megtilt, tilt', 'example_en' => 'She was forbidden from entering the restricted area.'],
            ['infinitive' => 'forget', 'past_simple' => 'forgot', 'past_participle' => 'forgotten', 'meaning_hu' => 'elfelejt, feledékeny', 'example_en' => 'Don\'t forget to call your mother on her birthday.'],
            ['infinitive' => 'forgive', 'past_simple' => 'forgave', 'past_participle' => 'forgiven', 'meaning_hu' => 'megbocsát, elenged', 'example_en' => 'She forgave him for the mistake he had made.'],
            ['infinitive' => 'foresee', 'past_simple' => 'foresaw', 'past_participle' => 'foreseen', 'meaning_hu' => 'előre lát, megjósol', 'example_en' => 'She foresaw the potential problems before they arose.'],
            ['infinitive' => 'freeze', 'past_simple' => 'froze', 'past_participle' => 'frozen', 'meaning_hu' => 'fagy, lefagyaszt', 'example_en' => 'The pond began to freeze in the cold winter months.'],
            ['infinitive' => 'get', 'past_simple' => 'got', 'past_participle' => 'got', 'meaning_hu' => 'kap, megszerez', 'example_en' => 'I need to get some milk from the shop.'],
            ['infinitive' => 'give', 'past_simple' => 'gave', 'past_participle' => 'given', 'meaning_hu' => 'ad, odaad', 'example_en' => 'She gave her friend a hug when they met.'],
            ['infinitive' => 'go', 'past_simple' => 'went', 'past_participle' => 'gone', 'meaning_hu' => 'megy, mehet', 'example_en' => 'She goes to the gym three times a week.'],
            ['infinitive' => 'grind', 'past_simple' => 'ground', 'past_participle' => 'ground', 'meaning_hu' => 'darál, zúz', 'example_en' => 'She ground the coffee beans fresh each morning.'],
            ['infinitive' => 'grow', 'past_simple' => 'grew', 'past_participle' => 'grown', 'meaning_hu' => 'nő, növekedik', 'example_en' => 'Children grow very quickly in their first few years.'],
            ['infinitive' => 'hang', 'past_simple' => 'hung', 'past_participle' => 'hung', 'meaning_hu' => 'felakaszt, lóg', 'example_en' => 'She hung her coat on the hook by the door.'],
            ['infinitive' => 'have', 'past_simple' => 'had', 'past_participle' => 'had', 'meaning_hu' => 'van neki, bír', 'example_en' => 'Do you have enough time to finish the work today?'],
            ['infinitive' => 'hear', 'past_simple' => 'heard', 'past_participle' => 'heard', 'meaning_hu' => 'hall, meghall', 'example_en' => 'She could not hear the music because of the noise.'],
            ['infinitive' => 'hide', 'past_simple' => 'hid', 'past_participle' => 'hidden', 'meaning_hu' => 'elrejt, bújócska', 'example_en' => 'The children hid behind the curtains to surprise her.'],
            ['infinitive' => 'hit', 'past_simple' => 'hit', 'past_participle' => 'hit', 'meaning_hu' => 'üt, eltalál', 'example_en' => 'The ball hit the window and broke it.'],
            ['infinitive' => 'hold', 'past_simple' => 'held', 'past_participle' => 'held', 'meaning_hu' => 'tart, fog', 'example_en' => 'She held the baby carefully in her arms.'],
            ['infinitive' => 'hurt', 'past_simple' => 'hurt', 'past_participle' => 'hurt', 'meaning_hu' => 'fáj, megsért', 'example_en' => 'She hurt her knee while running on the wet path.'],
            ['infinitive' => 'keep', 'past_simple' => 'kept', 'past_participle' => 'kept', 'meaning_hu' => 'tart, megtart', 'example_en' => 'She keeps all her old letters in a special box.'],
            ['infinitive' => 'kneel', 'past_simple' => 'knelt', 'past_participle' => 'knelt', 'meaning_hu' => 'letérdel, térdel', 'example_en' => 'She knelt down to help the child tie his shoes.'],
            ['infinitive' => 'know', 'past_simple' => 'knew', 'past_participle' => 'known', 'meaning_hu' => 'tud, ismer', 'example_en' => 'Do you know the name of this street?'],
            ['infinitive' => 'lay', 'past_simple' => 'laid', 'past_participle' => 'laid', 'meaning_hu' => 'lefektet, tojik', 'example_en' => 'She laid the baby gently in the cot.'],
            ['infinitive' => 'lead', 'past_simple' => 'led', 'past_participle' => 'led', 'meaning_hu' => 'vezet, ólom', 'example_en' => 'She leads the team with great confidence.'],
            ['infinitive' => 'leap', 'past_simple' => 'leapt', 'past_participle' => 'leapt', 'meaning_hu' => 'ugrik, ugrás', 'example_en' => 'She leapt over the puddle on the path.'],
            ['infinitive' => 'leave', 'past_simple' => 'left', 'past_participle' => 'left', 'meaning_hu' => 'elhagy, otthagy', 'example_en' => 'She left the office early because of a headache.'],
            ['infinitive' => 'lend', 'past_simple' => 'lent', 'past_participle' => 'lent', 'meaning_hu' => 'kölcsönad, ad', 'example_en' => 'She lent her friend some money for the trip.'],
            ['infinitive' => 'let', 'past_simple' => 'let', 'past_participle' => 'let', 'meaning_hu' => 'enged, hagy', 'example_en' => 'Let me help you carry those heavy bags.'],
            ['infinitive' => 'lose', 'past_simple' => 'lost', 'past_participle' => 'lost', 'meaning_hu' => 'elveszít, veszít', 'example_en' => 'She does not like to lose at board games.'],
            ['infinitive' => 'make', 'past_simple' => 'made', 'past_participle' => 'made', 'meaning_hu' => 'csinál, gyárt', 'example_en' => 'She makes her own bread every weekend.'],
            ['infinitive' => 'mean', 'past_simple' => 'meant', 'past_participle' => 'meant', 'meaning_hu' => 'jelent, átlag', 'example_en' => 'What does this word mean in Hungarian?'],
            ['infinitive' => 'meet', 'past_simple' => 'met', 'past_participle' => 'met', 'meaning_hu' => 'találkozik, megismer', 'example_en' => 'She arranged to meet her friend at the coffee shop.'],
            ['infinitive' => 'mow', 'past_simple' => 'mowed', 'past_participle' => 'mown', 'meaning_hu' => 'nyír, kaszál', 'example_en' => 'She mowed the lawn every Saturday morning.'],
            ['infinitive' => 'offset', 'past_simple' => 'offset', 'past_participle' => 'offset', 'meaning_hu' => 'ellensúlyoz, ellentételez', 'example_en' => 'She offset the extra costs with savings elsewhere.'],
            ['infinitive' => 'overcome', 'past_simple' => 'overcame', 'past_participle' => 'overcome', 'meaning_hu' => 'legyőz, leküzd', 'example_en' => 'She overcame her fear of public speaking.'],
            ['infinitive' => 'oversee', 'past_simple' => 'oversaw', 'past_participle' => 'overseen', 'meaning_hu' => 'felügyel, irányít', 'example_en' => 'She oversaw the construction of the new building.'],
            ['infinitive' => 'pay', 'past_simple' => 'paid', 'past_participle' => 'paid', 'meaning_hu' => 'fizet, fizetés', 'example_en' => 'She pays her bills on time every month.'],
            ['infinitive' => 'prove', 'past_simple' => 'proved', 'past_participle' => 'proven', 'meaning_hu' => 'bizonyít, igazol', 'example_en' => 'She proved that her method was more effective.'],
            ['infinitive' => 'put', 'past_simple' => 'put', 'past_participle' => 'put', 'meaning_hu' => 'tesz, helyez', 'example_en' => 'She put the flowers in a vase on the kitchen table.'],
            ['infinitive' => 'quit', 'past_simple' => 'quit', 'past_participle' => 'quit', 'meaning_hu' => 'felhagy, abbahagyja', 'example_en' => 'She quit her job to start her own business.'],
            ['infinitive' => 'read', 'past_simple' => 'read', 'past_participle' => 'read', 'meaning_hu' => 'olvas, értelmez', 'example_en' => 'She reads a book every night before going to sleep.'],
            ['infinitive' => 'repay', 'past_simple' => 'repaid', 'past_participle' => 'repaid', 'meaning_hu' => 'visszafizet, meghálálja', 'example_en' => 'She repaid the loan within the agreed time.'],
            ['infinitive' => 'rid', 'past_simple' => 'rid', 'past_participle' => 'rid', 'meaning_hu' => 'megszabadul, megtisztít', 'example_en' => 'She finally got rid of all the old clothes she never wore.'],
            ['infinitive' => 'ride', 'past_simple' => 'rode', 'past_participle' => 'ridden', 'meaning_hu' => 'lovagol, utazik', 'example_en' => 'She goes for a bike ride every morning before work.'],
            ['infinitive' => 'ring', 'past_simple' => 'rang', 'past_participle' => 'rung', 'meaning_hu' => 'gyűrű, cseng', 'example_en' => 'The phone rang loudly in the middle of the meeting.'],
            ['infinitive' => 'rise', 'past_simple' => 'rose', 'past_participle' => 'risen', 'meaning_hu' => 'emelkedik, felkel', 'example_en' => 'The sun rises early in the morning during summer.'],
            ['infinitive' => 'run', 'past_simple' => 'ran', 'past_participle' => 'run', 'meaning_hu' => 'fut, szalad', 'example_en' => 'She runs five kilometres every morning to stay fit.'],
            ['infinitive' => 'say', 'past_simple' => 'said', 'past_participle' => 'said', 'meaning_hu' => 'mond, szól', 'example_en' => 'She said goodbye and walked out of the door.'],
            ['infinitive' => 'see', 'past_simple' => 'saw', 'past_participle' => 'seen', 'meaning_hu' => 'lát, megért', 'example_en' => 'Can you see the mountains from your window?'],
            ['infinitive' => 'seek', 'past_simple' => 'sought', 'past_participle' => 'sought', 'meaning_hu' => 'keres, törekszik', 'example_en' => 'She sought advice from an experienced mentor.'],
            ['infinitive' => 'sell', 'past_simple' => 'sold', 'past_participle' => 'sold', 'meaning_hu' => 'elad, árul', 'example_en' => 'She decided to sell her old car and buy a new one.'],
            ['infinitive' => 'send', 'past_simple' => 'sent', 'past_participle' => 'sent', 'meaning_hu' => 'küld, elküld', 'example_en' => 'She sent a postcard from every city she visited.'],
            ['infinitive' => 'set', 'past_simple' => 'set', 'past_participle' => 'set', 'meaning_hu' => 'készlet, beállít', 'example_en' => 'She set the table for dinner before her guests arrived.'],
            ['infinitive' => 'sew', 'past_simple' => 'sewed', 'past_participle' => 'sewn', 'meaning_hu' => 'varr, hímez', 'example_en' => 'She sewed a button back onto her coat.'],
            ['infinitive' => 'shake', 'past_simple' => 'shook', 'past_participle' => 'shaken', 'meaning_hu' => 'ráz, remeg', 'example_en' => 'She shook her head to say no to the question.'],
            ['infinitive' => 'shed', 'past_simple' => 'shed', 'past_participle' => 'shed', 'meaning_hu' => 'fészer, elveszít', 'example_en' => 'The tree shed its leaves in autumn.'],
            ['infinitive' => 'shine', 'past_simple' => 'shone', 'past_participle' => 'shone', 'meaning_hu' => 'ragyog, fényesít', 'example_en' => 'The sun shone brightly all afternoon.'],
            ['infinitive' => 'shoot', 'past_simple' => 'shot', 'past_participle' => 'shot', 'meaning_hu' => 'lő, hajt', 'example_en' => 'She loves to shoot photos in the early morning light.'],
            ['infinitive' => 'show', 'past_simple' => 'showed', 'past_participle' => 'shown', 'meaning_hu' => 'mutat, műsor', 'example_en' => 'She showed him around the new office building.'],
            ['infinitive' => 'shrink', 'past_simple' => 'shrank', 'past_participle' => 'shrunk', 'meaning_hu' => 'zsugorodik, zsugorít', 'example_en' => 'The fabric shrank after being washed at high temperature.'],
            ['infinitive' => 'shut', 'past_simple' => 'shut', 'past_participle' => 'shut', 'meaning_hu' => 'zár, becsuk', 'example_en' => 'She shut the window because of the cold wind.'],
            ['infinitive' => 'sing', 'past_simple' => 'sang', 'past_participle' => 'sung', 'meaning_hu' => 'énekel, dalol', 'example_en' => 'She loves to sing in the shower every morning.'],
            ['infinitive' => 'sink', 'past_simple' => 'sank', 'past_participle' => 'sunk', 'meaning_hu' => 'mosogató, süllyed', 'example_en' => 'The boat slowly sank to the bottom of the lake.'],
            ['infinitive' => 'sit', 'past_simple' => 'sat', 'past_participle' => 'sat', 'meaning_hu' => 'ül, leül', 'example_en' => 'She sat down in the armchair and picked up her book.'],
            ['infinitive' => 'sleep', 'past_simple' => 'slept', 'past_participle' => 'slept', 'meaning_hu' => 'alszik, alvás', 'example_en' => 'She needs at least eight hours of sleep every night.'],
            ['infinitive' => 'slide', 'past_simple' => 'slid', 'past_participle' => 'slid', 'meaning_hu' => 'csúszik, csúszda', 'example_en' => 'The children slid down the hill on their sledges.'],
            ['infinitive' => 'speak', 'past_simple' => 'spoke', 'past_participle' => 'spoken', 'meaning_hu' => 'beszél, szól', 'example_en' => 'She speaks three languages fluently.'],
            ['infinitive' => 'spend', 'past_simple' => 'spent', 'past_participle' => 'spent', 'meaning_hu' => 'költ, tölt', 'example_en' => 'She spends most of her free time reading books.'],
            ['infinitive' => 'spin', 'past_simple' => 'spun', 'past_participle' => 'spun', 'meaning_hu' => 'pörget, forog', 'example_en' => 'She spun the wheel and waited for the result.'],
            ['infinitive' => 'spit', 'past_simple' => 'spat', 'past_participle' => 'spat', 'meaning_hu' => 'köp, nyárs', 'example_en' => 'She spat out the bitter medicine immediately.'],
            ['infinitive' => 'split', 'past_simple' => 'split', 'past_participle' => 'split', 'meaning_hu' => 'feloszt, meghasad', 'example_en' => 'She split the cost equally between the two of them.'],
            ['infinitive' => 'spread', 'past_simple' => 'spread', 'past_participle' => 'spread', 'meaning_hu' => 'terjeszt, ken', 'example_en' => 'She spread butter on the toast for breakfast.'],
            ['infinitive' => 'stand', 'past_simple' => 'stood', 'past_participle' => 'stood', 'meaning_hu' => 'áll, elvisel', 'example_en' => 'She stood at the window and watched the rain fall.'],
            ['infinitive' => 'steal', 'past_simple' => 'stole', 'past_participle' => 'stolen', 'meaning_hu' => 'lop, ellop', 'example_en' => 'Someone stole her bicycle from outside the shop.'],
            ['infinitive' => 'stick', 'past_simple' => 'stuck', 'past_participle' => 'stuck', 'meaning_hu' => 'bot, ragaszt', 'example_en' => 'She stuck the poster on the wall with tape.'],
            ['infinitive' => 'sting', 'past_simple' => 'stung', 'past_participle' => 'stung', 'meaning_hu' => 'csíp, fullánk', 'example_en' => 'She was stung by a bee in the garden.'],
            ['infinitive' => 'strike', 'past_simple' => 'struck', 'past_participle' => 'struck', 'meaning_hu' => 'üt, sztrájkol', 'example_en' => 'The clock struck twelve at midnight.'],
            ['infinitive' => 'swear', 'past_simple' => 'swore', 'past_participle' => 'sworn', 'meaning_hu' => 'esküszik, káromkodik', 'example_en' => 'She swore to tell the truth in court.'],
            ['infinitive' => 'sweep', 'past_simple' => 'swept', 'past_participle' => 'swept', 'meaning_hu' => 'söpör, elsöpör', 'example_en' => 'She swept the kitchen floor every morning.'],
            ['infinitive' => 'swell', 'past_simple' => 'swelled', 'past_participle' => 'swollen', 'meaning_hu' => 'dagad, feldagad', 'example_en' => 'Her ankle swelled after the injury.'],
            ['infinitive' => 'swim', 'past_simple' => 'swam', 'past_participle' => 'swum', 'meaning_hu' => 'úszik, úszás', 'example_en' => 'She swims in the local pool three times a week.'],
            ['infinitive' => 'swing', 'past_simple' => 'swung', 'past_participle' => 'swung', 'meaning_hu' => 'lendül, hinta', 'example_en' => 'The children loved to swing in the garden.'],
            ['infinitive' => 'take', 'past_simple' => 'took', 'past_participle' => 'taken', 'meaning_hu' => 'vesz, elvesz', 'example_en' => 'She takes the bus to work every morning.'],
            ['infinitive' => 'teach', 'past_simple' => 'taught', 'past_participle' => 'taught', 'meaning_hu' => 'tanít, oktat', 'example_en' => 'She teaches English to young children at a primary school.'],
            ['infinitive' => 'tear', 'past_simple' => 'tore', 'past_participle' => 'torn', 'meaning_hu' => 'könny, szakít', 'example_en' => 'She tore the letter into pieces after reading it.'],
            ['infinitive' => 'tell', 'past_simple' => 'told', 'past_participle' => 'told', 'meaning_hu' => 'mond, elmond', 'example_en' => 'She told her children a story before they went to sleep.'],
            ['infinitive' => 'think', 'past_simple' => 'thought', 'past_participle' => 'thought', 'meaning_hu' => 'gondol, hisz', 'example_en' => 'She thinks about her future every day.'],
            ['infinitive' => 'throw', 'past_simple' => 'threw', 'past_participle' => 'thrown', 'meaning_hu' => 'dob, hajít', 'example_en' => 'She threw the ball to her dog in the garden.'],
            ['infinitive' => 'thrust', 'past_simple' => 'thrust', 'past_participle' => 'thrust', 'meaning_hu' => 'lök, erő', 'example_en' => 'She thrust the document across the table.'],
            ['infinitive' => 'undergo', 'past_simple' => 'underwent', 'past_participle' => 'undergone', 'meaning_hu' => 'alávet magát, átesik', 'example_en' => 'She underwent surgery to repair the injury.'],
            ['infinitive' => 'underlie', 'past_simple' => 'underlay', 'past_participle' => 'underlain', 'meaning_hu' => 'alapját képezi, rejlik', 'example_en' => 'Several factors underlie the success of the project.'],
            ['infinitive' => 'understand', 'past_simple' => 'understood', 'past_participle' => 'understood', 'meaning_hu' => 'megért, felfog', 'example_en' => 'She did not understand the instructions at first.'],
            ['infinitive' => 'undertake', 'past_simple' => 'undertook', 'past_participle' => 'undertaken', 'meaning_hu' => 'vállal, elvállal', 'example_en' => 'She undertook the most challenging part of the project.'],
            ['infinitive' => 'upset', 'past_simple' => 'upset', 'past_participle' => 'upset', 'meaning_hu' => 'felzaklat, ideges', 'example_en' => 'She was upset by the unexpected news.'],
            ['infinitive' => 'wake', 'past_simple' => 'woke', 'past_participle' => 'woken', 'meaning_hu' => 'felébred, felkelt', 'example_en' => 'She woke up early to prepare for the long journey.'],
            ['infinitive' => 'wear', 'past_simple' => 'wore', 'past_participle' => 'worn', 'meaning_hu' => 'visel, hord', 'example_en' => 'She wears a jacket every day because the office is cold.'],
            ['infinitive' => 'weave', 'past_simple' => 'wove', 'past_participle' => 'woven', 'meaning_hu' => 'sző, fon', 'example_en' => 'She wove the threads together to make a scarf.'],
            ['infinitive' => 'wed', 'past_simple' => 'wed', 'past_participle' => 'wed', 'meaning_hu' => 'esküszik, összeköt', 'example_en' => 'They wed in a small ceremony in the countryside.'],
            ['infinitive' => 'weep', 'past_simple' => 'wept', 'past_participle' => 'wept', 'meaning_hu' => 'sír, könnyek', 'example_en' => 'She wept quietly when she heard the sad news.'],
            ['infinitive' => 'win', 'past_simple' => 'won', 'past_participle' => 'won', 'meaning_hu' => 'nyer, győz', 'example_en' => 'She won the first prize in the national writing competition.'],
            ['infinitive' => 'withdraw', 'past_simple' => 'withdrew', 'past_participle' => 'withdrawn', 'meaning_hu' => 'visszavon, kivesz', 'example_en' => 'She withdrew her application after the interview.'],
            ['infinitive' => 'write', 'past_simple' => 'wrote', 'past_participle' => 'written', 'meaning_hu' => 'ír, felír', 'example_en' => 'She writes in her journal every evening before bed.'],
        ];

        $now = now();

        IrregularVerb::upsert(
            array_map(fn ($v) => array_merge($v, ['notes' => null, 'created_at' => $now, 'updated_at' => $now]), $verbs),
            ['infinitive'],
            ['past_simple', 'past_participle', 'meaning_hu', 'example_en', 'updated_at']
        );
    }
}
